kops create cluster \
   --name="ibrahimsite.xyz" #replace with clustername\  
   --cloud="aws" \
   --network-cidr="192.168.0.0/16" \
   --networking="weave" \
   --master-zones="us-east-2a,us-east-2b,us-east-2c" \
   --zones="us-east-2a,us-east-2b,us-east-2c" \
   --master-size="t2.medium" \
   --master-count="3" \
   --node-size="t2.medium" \
   --node-count="3" \
   --state="s3://ibrahimsite.xyz" \
   --topology="private" \
   --subnets="subnet-0ced12342,subnet-036dw235fwr32,subnet-0w54fgrgt45232" #private-subnet\
   --bastion="true" \
   --utility-subnets="subnet-09infdsjtr2fdf5fe,subnet-43sf54dfsafwe43rg,subnet-04ft4vfdgbthrhgv"#public subnet for bastion \
   --vpc="vpc-03rrtgvtr5525tfvdfv" #vpcid\
   --dry-run -o yaml > cluster.yaml
